source "https://rubygems.org"

ruby "3.1.4"
gem "sinatra"
gem "sinatra-contrib"
gem "erubis"
gem "pg"
gem "bcrypt"
gem "minitest"
gem "rack-test"
gem "redcarpet"

group :production do
  gem "puma"
end